; Runtime PHP settings for production
memory_limit = 512M
max_execution_time = 300
post_max_size = 220M
upload_max_filesize = 210M
max_input_vars = 3000
date.timezone = Africa/Blantyre
expose_php = Off
log_errors = On
error_log = /proc/self/fd/2
